### ISSUE TITLE
怎么创建像BlendAPI这样的文档doc的工程呢？

### ISSUE THREAD

**Issue by iqiancheng** [Clouda-team/BlendAPI#4]
http://clouda.baidu.com/blendui/introduction/introduction

是纯html的吗？需要什么框架来创建doc文档么，我有个项目想开源，写一些介绍文档，希望能够做的和BlendAPI这样漂亮的文档，便于开发者阅读。

**Comment by cnberg** [comment]
我们用markdown生成html然后套样式实现的

## 

Sincerely
Berg Lei

**Comment by iqiancheng** [comment]
thx,方法很可取。
我想自己尝试做个通用点的，然后做个开源给广大代码猴用 ：）

**Comment by cnberg** [comment]
你可以看看 jsduck，我们内部部分文档用这个的，也还扩展性挺强，js注释 - 文档。

而blend的文档的思路更加像一个基于markdown的blog，类似 http://anchorcms.com/，是从markdown - html
- css + js = 文档

---

Yours sincerely
berg
http://cnberg.com
@cnberg
